Repository llocr/SpartaEats_Customer, pull requests merged in 2024-06, with the labels that each got.

#8 feat : 메뉴 단건조회/다건조회 구현
  src/main/java/like/heocholi/spartaeats/controller/MenuController.java
  src/main/java/like/heocholi/spartaeats/repository/MenuRepository.java
  src/main/java/like/heocholi/spartaeats/service/MenuService.java
Labels: enhancement

#10 feat : 장바구니 관련 기능 구현
  src/main/java/like/heocholi/spartaeats/controller/CartController.java
  src/main/java/like/heocholi/spartaeats/dto/CartRequestDTO.java
  src/main/java/like/heocholi/spartaeats/dto/CartResponseDTO.java
  src/main/java/like/heocholi/spartaeats/entity/Cart.java
  src/main/java/like/heocholi/spartaeats/entity/Menu.java
  src/main/java/like/heocholi/spartaeats/entity/Store.java
  src/main/java/like/heocholi/spartaeats/exception/CartException.java
  src/main/java/like/heocholi/spartaeats/exception/GlobalExceptionHandler.java
  src/main/java/like/heocholi/spartaeats/repository/CartRepository.java
  src/main/java/like/heocholi/spartaeats/repository/MenuRepository.java
  src/main/java/like/heocholi/spartaeats/service/CartService.java
Labels: enhancement

#11 feat : 주문 관련 기능 구현
  src/main/java/like/heocholi/spartaeats/constants/OrderState.java
  src/main/java/like/heocholi/spartaeats/controller/OrderController.java
  src/main/java/like/heocholi/spartaeats/dto/OrderListResponseDTO.java
  src/main/java/like/heocholi/spartaeats/dto/OrderResponseDTO.java
  src/main/java/like/heocholi/spartaeats/entity/Order.java
  src/main/java/like/heocholi/spartaeats/entity/OrderMenu.java
  src/main/java/like/heocholi/spartaeats/exception/ContentNotFoundException.java
  src/main/java/like/heocholi/spartaeats/exception/GlobalExceptionHandler.java
  src/main/java/like/heocholi/spartaeats/exception/OrderException.java
  src/main/java/like/heocholi/spartaeats/repository/OrderMenuRepository.java
  src/main/java/like/heocholi/spartaeats/repository/OrderRepository.java
  src/main/java/like/heocholi/spartaeats/service/OrderService.java
Labels: enhancement

#22 refactor/#18 : 메뉴 리팩토링
  src/main/java/like/heocholi/spartaeats/constants/ErrorType.java
  src/main/java/like/heocholi/spartaeats/controller/MenuController.java
  src/main/java/like/heocholi/spartaeats/exception/MenuException.java
  src/main/java/like/heocholi/spartaeats/service/MenuService.java
Labels: refactor 🔧

#23 [REFECTOR] 유저 리팩토링
  src/main/java/like/heocholi/spartaeats/controller/CustomerController.java
  src/main/java/like/heocholi/spartaeats/dto/SignupResponseDto.java
  src/main/java/like/heocholi/spartaeats/exception/CustomerException.java
  src/main/java/like/heocholi/spartaeats/jwt/JwtAuthenticationFilter.java
  src/main/java/like/heocholi/spartaeats/service/CustomerService.java
Labels: refactor 🔧

#17 Feat/#1/stores
  src/main/java/like/heocholi/spartaeats/controller/StoreController.java
  src/main/java/like/heocholi/spartaeats/dto/StorePageResponseDto.java
  src/main/java/like/heocholi/spartaeats/dto/StoreRequestDto.java
  src/main/java/like/heocholi/spartaeats/dto/StoreResponseDto.java
  src/main/java/like/heocholi/spartaeats/entity/Manager.java
  src/main/java/like/heocholi/spartaeats/entity/Store.java
  src/main/java/like/heocholi/spartaeats/repository/MenuRepository.java
  src/main/java/like/heocholi/spartaeats/repository/StoreRepository.java
  src/main/java/like/heocholi/spartaeats/service/StoreService.java
Labels: feat ✨

#28 fix/#20 : CartRequestDTO 수정 & 주문 시 totalPrice가 제대로 계산되지 않는 문제 해결
  src/main/java/like/heocholi/spartaeats/dto/CartRequestDTO.java
  src/main/java/like/heocholi/spartaeats/service/CartService.java
  src/main/java/like/heocholi/spartaeats/service/OrderService.java
Labels: bug 🐛

#32 Refactor/#27/stores
  src/main/java/like/heocholi/spartaeats/constants/ErrorType.java
  src/main/java/like/heocholi/spartaeats/controller/StoreController.java
  src/main/java/like/heocholi/spartaeats/dto/StoreRequestDto.java
  src/main/java/like/heocholi/spartaeats/dto/StoreResponseDto.java
  src/main/java/like/heocholi/spartaeats/exception/StoreException.java
  src/main/java/like/heocholi/spartaeats/service/StoreService.java
Labels: refactor 🔧

#38 Refactor/#37/store
  src/main/java/like/heocholi/spartaeats/constants/ErrorType.java
  src/main/java/like/heocholi/spartaeats/controller/StoreController.java
  src/main/java/like/heocholi/spartaeats/dto/StoreListResponseDto.java
  src/main/java/like/heocholi/spartaeats/dto/StorePageResponseDto.java
  src/main/java/like/heocholi/spartaeats/repository/StoreRepository.java
  src/main/java/like/heocholi/spartaeats/service/StoreService.java
Labels: refactor 🔧

#34 Feature/#30/like
  src/main/java/like/heocholi/spartaeats/constants/ErrorType.java
  src/main/java/like/heocholi/spartaeats/controller/LikeController.java
  src/main/java/like/heocholi/spartaeats/dto/ResponseMessage.java
  src/main/java/like/heocholi/spartaeats/entity/Like.java
  src/main/java/like/heocholi/spartaeats/entity/Review.java
  src/main/java/like/heocholi/spartaeats/exception/LikeException.java
  src/main/java/like/heocholi/spartaeats/repository/LikeRepository.java
  src/main/java/like/heocholi/spartaeats/service/LikeService.java
Labels: feat ✨, help 🤯
